### PR TITLE
Update customcolors.js

### PR DESCRIPTION
**Pull request by ghost**
added custom symbol color

### CODE REVIEW

**Comment by SilverTactic** [comment]
Are you sure you did this right? You replaced a lot of other things and your indention for the custom symbol color command is off (probably along with the rest of the stuff you changed) >.>

**Comment by SilverTactic** [comment]
Additionally, I've been hearing some of the old alpha/origin staff say that this Richard Adams dude kept pestering admins to accept PRs that were often stolen from others, sooo I'm not sure how I feel about this PR :I

**Comment by ghost** [comment]
i am not stoling anything
and i dont claim every thing was made by me..
i customized some plugins but not stolen or something

**Comment by ghost** [comment]
the plugin customized by me i put my name in their customized by richardadams

**Comment by jd4564** [comment]
This isn't even close to being functional and I'm not sure users really need custom symbol colours.

**Pull request closed without merging**
