### PR TITLE
Update economy.js

### PR DESCRIPTION
**Pull request by aakashrajput**
added givemoney and takemoney popup it also shows the user total amount

### CODE REVIEW

**Comment by SilverTactic** [comment]
The changes are fine, but you need to indent your code correctly

**Comment by aakashrajput** [comment]
indent?

**Comment by SilverTactic** [comment]
Yknow, making the code neat and stuff by aligning it with the rest and adding proper spacing using tabs

**Comment by aakashrajput** [comment]
huh? fine next time ill remember this

**Comment by CharizardtheFireMage** [comment]
What is the use of `Wisp.hashColor (user.id)` for the popup message for when you do givebucks and takebucks? That seems really unimportant to the command in general.

**Comment by aakashrajput** [comment]
to get the username color in popup it looks good tho

**Comment by CharizardtheFireMage** [comment]
> good

To be honest, it looks fine without `Wisp.nameColor` being defined. Plus this PR feels like as if it doesn't help out the server at all.

**Comment by aakashrajput** [comment]
i just made it more attractive for the user who is getting money .  its just a style edit not any type of new code that can help server. and it upto wisp developers they want it or not @CharizardtheFireMage

**Comment by SilverTactic** [comment]
I'll admit that all the extra colors and stuff aren't really needed, but I think it's kinda important to give other users popup notifs when they receive bucks or have bucks taken from them @CharizardtheFireMage

**Comment by aakashrajput** [comment]
hmm that what i added here..

**Comment by SilverTactic** [comment]
ikik :P 
@Kevin199 You can fix the indentation by updating your pull request using your git shell (unless you don't know what that is)

**Comment by aakashrajput** [comment]
lol xD

**Comment by jd4564** [comment]
Merged in 611dfcae27140b58ff02274e06e762838d8822f3

**Comment by panpawn** [comment]
xDDDDDDDDDDDDdd

**Pull request closed without merging**
