### PR TITLE
add wssb 

### PR DESCRIPTION
**Pull request by Volco**
its... finally done

### CODE REVIEW

**Comment by trixiemiller** [comment]
you dont need statuses.js nor rulesets.js at all i think
for moves/abilities, simply just put the new ones in, it makes upstream merging with main less likely to cause issues since they often refactor moves causes crashes when you use them in this format

**Comment by SilverTactic** [comment]
o.o
You don't need to add everything into those files. You just need to add the stuff you wanna change or the stuff you wanna add lol

**Comment by panpawn** [comment]
ok
do
not
make
more 
prs
for
this
again

**Comment by panpawn** [comment]
im assuming this is being taken over by https://github.com/jd4564/Pokemon-Showdown/pull/118 and if it's not im going to flip a table

**Pull request closed without merging**
