### PR TITLE
Add Custom Titles in profile

### PR DESCRIPTION
**Pull request by Darkero**

### CODE REVIEW

**Comment by CharizardtheFireMage** [comment]
@supersoniko Someone is using your customtitles plugin once again. FacePalm

**Comment by supersoniko** [comment]
hehe make sure to add appropriate credits next time ^^'

**Comment by Darkero** [comment]
Sorry, I didn't found any credits! D: I'll ask next time ^^'

**Comment by supersoniko** [comment]
Np I didn't implement it myself yet to wisp because the code needed some cleaning first

**Pull request closed without merging**
