### PR TITLE
Make icon command be a namespace command

### PR DESCRIPTION
**Pull request by Torpidwaters**

### CODE REVIEW

**Comment by panpawn** [comment]
Note how the major commands that use the namespace command format are things that accept several arguments, such as `/poll`, for example.  This only accepts either setting an icon or deleting an icon, and for that reason I don't think this is particularly needed due to that fact.

**Comment by Torpidwaters** [comment]
JD requested this change

**Comment by panpawn** [comment]
@jd4564 - if we're going with changes like this, then when will you decide to start using template strings?

**Comment by panpawn** [comment]
https://developers.google.com/web/updates/2015/01/ES6-Template-Strings?hl=en

**Pull request merged**
