### PR TITLE
Add PR as an alias for poll display

### PR DESCRIPTION
**Pull request by SerperiorBae**
Well just add it as a new command.
Im sure this is how I did it for gold if not its because im p fuckin tired.

### CODE REVIEW

**Comment by AlainDuhHero** [comment]
u were looking for an alias
Well..... do 
only

this.parse('/poll display');

Dunno burden the server with excess codes n_n

**Comment by SerperiorBae** [comment]
Yeah but if you do that its only gunna parse the non broadcasted one ?_?

**Comment by AlainDuhHero** [comment]
naah
if the user uses !pr
it wont

**Comment by panpawn** [comment]
> Im sure this is how I did it for gold if not its because im p fuckin tired.

lol, I made Gold's PR command

**Comment by panpawn** [comment]
@AlainDuhHero - you're an idiot

**Comment by panpawn** [comment]
`/pr` is currently an alias on Wisp as `/pickrandom`

**Pull request closed without merging**
