### PR TITLE
Create rps.js

### PR DESCRIPTION
**Pull request by KevinNeon**
just for some event or fun

### CODE REVIEW

**Comment by SilverTactic** [comment]
You didn't have to close it y'know. It seemed pretty interesting lol

**Comment by KevinNeon** [comment]
lolz well okiee xaa

**Comment by ashyudhajit** [comment]
close this PR . This is incompatible with jd's economy code so this will break the server

**Comment by supersoniko** [comment]
Please update the code to be compatible with wisp, if you're not planning on updating the code you can close this pr. Feel free to contact a dev if you need help!

**Comment by jd4564** [comment]
As mentioned above this needs updated and tested to use `Economy.readMoney` and `Economy.writeMoney` instead of `Db`

**Pull request closed without merging**
