### PR TITLE
Change PSGO Pack Opening Visual

### PR DESCRIPTION
**Pull request by Torpidwaters**
-Requested by Kanabae

### CODE REVIEW

**Comment by panpawn** [comment]
Screen cap?

**Comment by Torpidwaters** [comment]
untitled

**Comment by Torpidwaters** [comment]
That is what it looks like, but it's from a really tiny monitor cuz i'm in a library atm.  I can upload one from a normal sized screen later tonight if you'd like.  The card picture is the same size as it is in !card.

**Comment by Tailzz** [comment]
This is going to look pretty bad for anyone on a phone or similar sized device. The current openpack display could be improved upon but this isn't the way to go about it.

**Comment by Torpidwaters** [comment]
http://imgur.com/QVPiMym http://imgur.com/zitgi98 - 2 pictures from mobile on a screen small even for a smartphone.  It actually does a better job showing cards than the current system would provide.  Also, once the top and bottom bars auto collapsed you could see significantly more as well.  I actually see this as an improvement in functionality for small screens.

**Comment by panpawn** [comment]
An iPad is not a phone.

**Comment by Torpidwaters** [comment]
That wasn't an iPad it was an iphone

**Comment by panpawn** [comment]
Then that's one big iPhone.

Keep in mind phones come in all different shapes and sizes,  along with different screen resolutions, too.

**Pull request closed without merging**
