### PR TITLE
Gangs and Fixes

### PR DESCRIPTION
**Pull request by austin0602**

### CODE REVIEW

**Review by KewlStatics — APPROVED** [review]
Good Changing lol! It was professionally done!

**Comment by KewlStatics** [comment]
But Shouldn't The sqlite3 be defined properly
I tried this code it made a crash

**Comment by KewlStatics** [comment]
My Bad Dint check app.js

**Comment by austin0602** [comment]
okay didn't mean to put these in the same PR but it is all ready so why not

**Comment by austin0602** [comment]
im going to just make a new one

**Pull request closed without merging**
