### PR TITLE
Updates to the claim command and other commands

### PR DESCRIPTION
**Pull request by CharizardtheFireMage**
1) Remove whitetrail spacing in takecredits and givecredits
2) Idk if grammar is necessary for both of those commands, but I decided to do it. Lol.
3) Update /claim so then whenever someone buys a ticket, a GLeader (particularly Kanabae) can respond and fill in for that order. I also updated how the raw message is sent through the room. Rather than a raw message, I replaced that with a "Credit Shop Alert" (for old times sake).
4) Reword some errorReplys to some commands and restrict displaying the Credit Shop to the Marketplace only.

### CODE REVIEW

**Comment by SilverTactic** [comment]
Do senior staff really need to know whether someone bought something from the credit shop lol

**Comment by CharizardtheFireMage** [comment]
Also the reason I added in a Senior Staff PM for when someone buys a ticket was in courtesy of Kanabae

**Comment by CharizardtheFireMage** [comment]
She says that it's hard to look in the Marketplace Staff room a lot of times, so a Senior Staff PM is fine with her. Is there another way that the PMs can redirect it to her rather than a senior staff?

**Comment by CharizardtheFireMage** [comment]
I can remove `Wisp.msgSeniorStaff` from the items of the claim command if you see that it really isn't needed for all the senior staff to be PM'ed about someone purchasing a ticket. But then that involves me making another PR on that.

**Pull request merged**
