### PR TITLE
Create draft.js

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by panpawn** [comment]
confused how this passed ``npm test``

**Comment by austin0602** [comment]
also, not sure how much it'll be used as most leagues do not use drafts and use the Gym Leaders, E4, Champion approach. but if it was used a lot, shouldn't we use sqlite3? as just about everything else is written in sqlite3. just a suggestion.

**Comment by ghost** [comment]
@panpawn the code works :( 
@austin0602  this file doesn't really need too much storage so a json based storage system works

**Comment by ghost** [comment]
@austin0602 the point of this code is for DRAFT leagues.

We could ofc make it so that only registered draft leagues may use it but idk tailz / jd's thoughts on that so i'll wait for them to make comments on this.

**Comment by austin0602** [comment]
understandable. i was just saying over time it will accumulate a whole lot. @xExecute

**Comment by panpawn** [comment]
Again, not sure how this passed ``npm test`` as it does not meet our coding standards of styling and whatnot.

>@panpawn the code works :(

... do you even know what ``npm test`` is?

**Comment by ghost** [comment]
@panpawn isn't used to do stuff like check to see if a if statement and a pair of () have a space between them and to make sure  the code is using tabs and not spaces?

**Pull request closed without merging**
