### PR TITLE
A (better?) poll design. (incomplete without CSS)

### PR DESCRIPTION
**Pull request by MasterFloat**
wisp-poll-design-started
wisp-poll-design-ended

### CODE REVIEW

**Comment by MasterFloat** [comment]
@panpawn Is there something I should enhance in this PR?

**Comment by panpawn** [comment]
@MasterFloat - jd and I discussed it briefly last night and we both are kind of thinking the same thing.  We both think this is a better design, but we don't think the color scheme goes with Wisp's CSS as well as the current poll system colors do.  Also, we don't think the "View Results" button should have it's own section like that.

**Comment by MasterFloat** [comment]
@panpawn 

wisp-poll-started
In this first screenshot the "green" button is in a :hover state.

wisp-poll-ended

If this is getting pushed, put [this CSS](http://pastebin.com/b1aHr3hU) in the top of custom.css in the "CUSTOM CLASSES" part. With this CSS the poll design will be complete.

**Comment by panpawn** [comment]
I like this better. @jd4564, @Tailzz - what are your thoughts?

**Comment by panpawn** [comment]
Just came to mind, the options _before_ you vote shouldn't be italic imo @MasterFloat

**Comment by MasterFloat** [comment]
@panpawn the text in the buttons?

**Comment by SilverTactic** [comment]
@panpawn wynaut? The italicized text doesn't look bad imo
In fact, I think they might actually look cooler if they're colored dark red or dark orange

**Comment by MasterFloat** [comment]
@SilverTactic probably because the italicization in the polls stands for the option the user voted for, and it'd be inappropriate to have it on all options.

**Comment by SilverTactic** [comment]
Oh I thought you were talking about the buttons

**Comment by MasterFloat** [comment]
I am.

**Comment by SilverTactic** [comment]
My bad, I misread that

**Comment by MasterFloat** [comment]
@panpawn anything else?

**Comment by panpawn** [comment]
Why did the poll say "Started by undefined"?

**Comment by MasterFloat** [comment]
@panpawn I was testing the poll design on a server with different codes from wisp

**Pull request merged**
